server:  
  port: ${PORT:0}
  error:
    include-message: always

spring:
  application:
    name: ms-customer
  data:
    mongodb:
#      host: localhost    
      host: mongodb
      port: 27017
      database: ms-customer
 
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration     

eureka:  client:    service-url:
      defaultZone: http://registry-service:8761/eureka    register-with-eureka: true
    fetch-registry: true  instance:
    instance-id: ${spring.application.name}:${random.value}

